"""Shared constants for the kickoff version."""

APP_NAME = "home cluster"
APP_SLUG = "home-cluster"
LOGGER_NAME = "home_cluster"

DEFAULT_NODE_NAME = "node"
HOME_SCHEDULER_NAME = "home scheduler"
HOME_SCHEDULER_SLUG = "home-scheduler"
HOME_COMPUTER_NAME = "home computer"
HOME_COMPUTER_SLUG = "home-computer"
HOME_CLIENT_NAME = "home client"
HOME_CLIENT_SLUG = "home-client"

RUNTIME_ROLE_WORKER = "worker"
RUNTIME_ROLE_CLIENT = "client"

DEFAULT_MULTICAST_GROUP = "224.0.0.251"
DEFAULT_DISCOVERY_PORT = 5353
DEFAULT_TCP_PORT = 52020
DEFAULT_DISCOVERY_TIMEOUT = 3.0
DEFAULT_BUFFER_SIZE = 2048
DEFAULT_MULTICAST_TTL = 255
DEFAULT_DISCOVERY_ATTEMPTS = 3
DEFAULT_DISCOVERY_RETRY_DELAY = 1.0
DEFAULT_MAIN_NODE_POLL_TIMEOUT = 1.0
DEFAULT_RUNTIME_SOCKET_TIMEOUT = 1.0
DEFAULT_TCP_CONNECT_TIMEOUT = 5.0
DEFAULT_HEARTBEAT_INTERVAL = 10.0
DEFAULT_HEARTBEAT_RETRY_COUNT = 3
DEFAULT_MAX_PROTOBUF_MESSAGE_SIZE = 65536

MDNS_SERVICE_TYPE = "_homecluster-hs._tcp.local."
MDNS_SERVICE_ROLE = HOME_SCHEDULER_SLUG
MDNS_RECORD_TTL = 120
MDNS_QUERY_UNICAST_RESPONSE = True

RUNTIME_MSG_REGISTER_WORKER = "REGISTER_WORKER"
RUNTIME_MSG_REGISTER_OK = "REGISTER_OK"
RUNTIME_MSG_HEARTBEAT = "HEARTBEAT"
RUNTIME_MSG_HEARTBEAT_OK = "HEARTBEAT_OK"
RUNTIME_MSG_CLIENT_JOIN = "CLIENT_JOIN"
RUNTIME_MSG_CLIENT_REQUEST = "CLIENT_REQUEST"
RUNTIME_MSG_CLIENT_RESPONSE = "CLIENT_RESPONSE"

WINDOWS_FIREWALL_RULE_NAME = "HomeClusterDiscoveryUDP"

MSG_DISCOVERY_TIMEOUT = "Discovery timed out."
MSG_MANUAL_PROMPT = "Enter peer host or host:port (leave blank to cancel): "
MSG_MANUAL_CANCELLED = "Manual input cancelled."
MSG_NOT_IMPLEMENTED = "Not implemented in kickoff version."