"""Shared constants for superweb-cluster."""

APP_NAME = "superweb-cluster"
APP_SLUG = "superweb-cluster"
LOGGER_NAME = "superweb_cluster"

DEFAULT_NODE_NAME = "node"
MAIN_NODE_NAME = "main node"
MAIN_NODE_SLUG = "main-node"
COMPUTE_NODE_NAME = "compute node"
COMPUTE_NODE_SLUG = "compute-node"
SUPERWEB_CLIENT_NAME = "superweb client"
SUPERWEB_CLIENT_SLUG = "superweb-client"

RUNTIME_ROLE_WORKER = "worker"
RUNTIME_ROLE_CLIENT = "client"

DEFAULT_MULTICAST_GROUP = "224.0.0.251"
DEFAULT_DISCOVERY_PORT = 5353
DEFAULT_TCP_PORT = 52020
DEFAULT_DISCOVERY_TIMEOUT = 3.0
DEFAULT_BUFFER_SIZE = 2048
DEFAULT_MULTICAST_TTL = 255
DEFAULT_DISCOVERY_ATTEMPTS = 3
DEFAULT_DISCOVERY_RETRY_DELAY = 1.0
DEFAULT_MAIN_NODE_POLL_TIMEOUT = 1.0
DEFAULT_RUNTIME_SOCKET_TIMEOUT = 1.0
DEFAULT_TCP_CONNECT_TIMEOUT = 5.0
DEFAULT_HEARTBEAT_INTERVAL = 10.0
DEFAULT_HEARTBEAT_RETRY_COUNT = 3
DEFAULT_MAX_PROTOBUF_MESSAGE_SIZE = 4 * 1024 * 1024

MDNS_SERVICE_TYPE = "_superweb-cluster._tcp.local."
MDNS_SERVICE_ROLE = MAIN_NODE_SLUG
MDNS_RECORD_TTL = 120
MDNS_QUERY_UNICAST_RESPONSE = True

RUNTIME_MSG_REGISTER_WORKER = "REGISTER_WORKER"
RUNTIME_MSG_REGISTER_OK = "REGISTER_OK"
RUNTIME_MSG_HEARTBEAT = "HEARTBEAT"
RUNTIME_MSG_HEARTBEAT_OK = "HEARTBEAT_OK"
RUNTIME_MSG_CLIENT_JOIN = "CLIENT_JOIN"
RUNTIME_MSG_CLIENT_REQUEST = "CLIENT_REQUEST"
RUNTIME_MSG_CLIENT_RESPONSE = "CLIENT_RESPONSE"
RUNTIME_MSG_TASK_ASSIGN = "TASK_ASSIGN"
RUNTIME_MSG_TASK_ACCEPT = "TASK_ACCEPT"
RUNTIME_MSG_TASK_FAIL = "TASK_FAIL"
RUNTIME_MSG_TASK_RESULT = "TASK_RESULT"

METHOD_FIXED_MATRIX_VECTOR_MULTIPLICATION = "fixed_matrix_vector_multiplication"
METHOD_SPATIAL_CONVOLUTION = "spatial_convolution"

DX12_BACKEND_DISABLED_REASON = (
    "DX12 backend is disabled due to a fatal instability bug that can trigger "
    "system-level crashes or power-protection events during benchmark execution. "
    "Do not use DX12 in this build."
)

STATUS_OK = 200
STATUS_ACCEPTED = 202
STATUS_BAD_REQUEST = 400
STATUS_NOT_FOUND = 404
STATUS_CONFLICT = 409
STATUS_INTERNAL_ERROR = 500

WINDOWS_FIREWALL_RULE_NAME = "SuperWebClusterDiscoveryUDP"

MSG_DISCOVERY_TIMEOUT = "Discovery timed out."
MSG_MANUAL_PROMPT = "Enter peer host or host:port (leave blank to cancel): "
MSG_MANUAL_CANCELLED = "Manual input cancelled."
MSG_NOT_IMPLEMENTED = "Not implemented in Sprint 1."
