"""GEMV input-dataset package."""

from .generator import generate_dataset
from .spec import (
    DEFAULT_CHUNK_VALUES,
    DEFAULT_COLS,
    LARGE_COLS,
    DEFAULT_MATRIX_SEED,
    DEFAULT_ROWS,
    LARGE_ROWS,
    MID_COLS,
    MID_ROWS,
    MEDIUM_COLS,
    MEDIUM_ROWS,
    DEFAULT_VECTOR_SEED,
    SMALL_COLS,
    SMALL_ROWS,
    TEST_COLS,
    TEST_ROWS,
    DatasetLayout,
    InputMatrixSpec,
    build_dataset_layout,
    build_input_matrix_spec,
    dataset_prefix_for_size,
    get_large_input_matrix_spec,
    get_mid_input_matrix_spec,
    get_small_input_matrix_spec,
    get_medium_input_matrix_spec,
    get_runtime_input_matrix_spec,
    get_test_input_matrix_spec,
    normalize_size_variant,
)
from .storage import compare_float32_vectors, dataset_is_generated, load_float32_file

__all__ = [
    "DEFAULT_CHUNK_VALUES",
    "DEFAULT_COLS",
    "LARGE_COLS",
    "DEFAULT_MATRIX_SEED",
    "DEFAULT_ROWS",
    "LARGE_ROWS",
    "MID_COLS",
    "MID_ROWS",
    "MEDIUM_COLS",
    "MEDIUM_ROWS",
    "DEFAULT_VECTOR_SEED",
    "SMALL_COLS",
    "SMALL_ROWS",
    "TEST_COLS",
    "TEST_ROWS",
    "DatasetLayout",
    "InputMatrixSpec",
    "build_dataset_layout",
    "build_input_matrix_spec",
    "compare_float32_vectors",
    "dataset_prefix_for_size",
    "dataset_is_generated",
    "generate_dataset",
    "get_large_input_matrix_spec",
    "get_mid_input_matrix_spec",
    "get_small_input_matrix_spec",
    "get_medium_input_matrix_spec",
    "get_runtime_input_matrix_spec",
    "get_test_input_matrix_spec",
    "load_float32_file",
    "normalize_size_variant",
]
